alias: Bewateringsadvies om 22u
trigger:
  - platform: time
    at: "22:00:00"
condition:
  - condition: state
    entity_id: input_boolean.bewatering_toestaan
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.grondvocht
    below: 30
  - condition: numeric_state
    entity_id: sensor.regen_1d
    below: 2
  - condition: numeric_state
    entity_id: sensor.regen_2d
    below: 2
  - condition: numeric_state
    entity_id: sensor.regen_laatste_24u
    below: 2
action:
  - service: notify.mobile_app_iphone_naam
    data:
      title: "\U0001F4A7 Bewatering aanbevolen"
      message: "De grond is droog en er wordt weinig regen verwacht. Wil je morgen bewateren? Zet 'Start bewatering' aan in Home Assistant."
mode: single
